### ISSUE TITLE
Changes from client #1

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/easton-caruthers-wp#8]
Create a "Player Registration" tab at the top next to the Home tab.
It should have two links underneath it. 
Player Registration 
Payment
Change "Sign Up" to "Payment" and make it a subordinate of the Player Registration tab.

I need the following information on the Player Registration page:

Player registration is a 2-step process.
1. Complete a player registration form for your player(s). You will be able to register up to 4 players on one form.

2. Submit payment for your player(s). You will be presented with a payment link after you submit your player registration form.

To register, please click on the Player Registration link below.

Player Registration (hyperlink this text with http://goo.gl/forms/2jo2giFulk)

That is all for the player registration page.

Please edit the following:

Change the "Schedule" tab to "Events"

Move the sign up link as stated above.

Change "Events Calendar" to "Calendar"
Change "Schedule" to "Game Schedules"
Leave Tournaments here with no changes

due:
11-6-15   7p

**Comment by rodneystrong** [comment]
Yo, status? If possible, put a new due date you can finish this by please, thanks.

**Comment by purplyrocky** [comment]
Updated due date 11-6-15 11:59pm
