### ISSUE TITLE
Paypal issue

### ISSUE THREAD

**Issue by rodneystrong** [EditLLC/easton-caruthers-wp#9]
issue with the PayPal button and I'm not quite sure how to fix it. From what I have been able to find so far, it may be a PHP session issue, but I'm not sure. Could you look into this for me?

What I noticed happening is an extra item will be added to the cart (but not every time). 

For example, last night when I was paying for my kids, I clicked on 2 Players $100. 

I was redirected to PayPal and I had the following in my cart:

1 Player $50

2 Players $100

Total $150

I tried it a couple different times on different devices and different browsers and have been able to reproduce the error only 2 or 3 times, but not consistently.

The others 5 or 6 times I tried to reproduce the error, it worked fine

>Meg, I may need to work with you on this. For the time being, research this issue and gather any relevant info you can and post it here.

due:
11-18-15    5p

**Comment by rodneystrong** [comment]
Any research on this ?

**Comment by vanderbeam** [comment]
I've enrolled like hundred kids into baseball at this point and haven't been able to reproduce this issue.
The closest I've gotten is not clearing the cart and then click a different amount of players (the previous selection is still in the cart).
I've also tried Googling around and it doesn't look like this is a known issue. I'll keep on it though.

**Comment by rodneystrong** [comment]
hahaha. yea i've enrolled a few kids myself on chrome and firefox but no issues.. I'll report back to client.

**Comment by rodneystrong** [comment]
tested in safari as well. 

it may have been an issue with this cart session being saved from before, thus duplicating his orders.

considering this resolved for now.
